DROP DATABASE IF EXISTS QA;

CREATE DATABASE QA;

DROP TABLE IF EXISTS questions, answers, answer_photos CASCADE;

-- USE QA;

CREATE TABLE questions (
  question_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id INT NOT NULL,
  question_body VARCHAR(1000) NOT NULL CHECK (question_body <> ''),
  question_date BIGINT NOT NULL,
  asker_name VARCHAR(60) NOT NULL CHECK (asker_name <> ''),
  asker_email VARCHAR(200),
  reported BOOLEAN DEFAULT false,
  question_helpfulness SMALLINT DEFAULT 0

);

CREATE TABLE answers (
  answer_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  question_id INT NOT NULL REFERENCES questions(question_id),
  body VARCHAR(1000) NOT NULL CHECK (body <> ''),
  answer_date BIGINT NOT NULL,
  answerer_name VARCHAR(60) NOT NULL CHECK (answerer_name <> ''),
  answerer_email VARCHAR(200),
  reported BOOLEAN DEFAULT false,
  helpfulness SMALLINT DEFAULT 0
);

CREATE TABLE answer_photos (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  answer_id INT REFERENCES answers(answer_id),
  url VARCHAR(1000) DEFAULT NULL
);


\timing

COPY questions
FROM '/Users/susanke/HackReactor/SDC/API-QA/Data/questions.csv'
DELIMITER ','
CSV HEADER;

ALTER TABLE ONLY questions
  ALTER COLUMN question_date TYPE TIMESTAMPTZ USING to_timestamp(question_date/1000) AT TIME ZONE 'UTC',
  ALTER COLUMN question_date SET DEFAULT NOW();

COPY answers
FROM '/Users/susanke/HackReactor/SDC/API-QA/Data/answers.csv'
DELIMITER ','
CSV HEADER;

ALTER TABLE ONLY answers
  ALTER COLUMN answer_date TYPE TIMESTAMPTZ USING to_timestamp(answer_date/1000) AT TIME ZONE 'UTC',
  ALTER COLUMN answer_date SET DEFAULT NOW();

COPY answer_photos
FROM '/Users/susanke/HackReactor/SDC/API-QA/Data/answers_photos.csv'
DELIMITER ','
CSV HEADER;
